name: lsmgridtrack
channels:
  - siboles
  - SimpleITK
  - conda-forge
dependencies:
  - simpleitk
  - vtk
  - pydantic
  - pandas
  - openpyxl
  - numpy
  - hypothesis
  - ca-certificates
  - openssl
  - pytest
  - pip
  - pip:
      - git+https://github.com/siboles/lsmgridtrack.git
