package:
  name: lsmgridtrack
  version: "0.3"

source:
  git_url: https://github.com/siboles/lsmgridtrack.git
  git_rev: 0.3

requirements:
  build:
    - python 3.6.13
    - future 0.18.2
    - pyyaml 5.4.1
    - vtk 8.2.0
    - simpleitk 1.2.0
    - numpy 1.19.5
    - openpyxl 3.0.7
    - febio 0.2.0
    - numba 0.53.1
  run:
    - python 3.6.13
    - future 0.18.2
    - pyyaml 5.4.1
    - vtk 8.2.0
    - simpleitk 1.2.0
    - numpy 1.19.5
    - openpyxl 3.0.7
    - febio 0.2.0
    - numba 0.53.1

test:
  imports:
    - lsmgridtrack

about:
  home: https://github.com/siboles/lsmgridtrack
  summary: 'A Python module providing a framework for deformable image registration of 3D images from multiphoton laser scanning microscopy. It is aimed at a technique involving the photobleaching of a 3D grid onto the image and then observing this grid region in unloaded and loaded states.
'
  license: BSD Clause-3
