package:
  name: lsmgridtrack
  version: 0.1

source:
  git_url: https://github.com/siboles/lsmgridtrack.git
  git_rev: 0.1

requirements:
  build:
    - python
    - future
    - pyyaml 5.4.1
    - vtk 8.2.0
    - simpleitk 1.2.0
    - numpy
    - openpyxl
    - febio 0.1.3
  run:
    - python
    - future
    - pyyaml 5.4.1
    - vtk 8.2.0
    - simpleitk 1.2.0
    - numpy
    - openpyxl
    - febio 0.1.3

test:
  imports:
    - lsmgridtrack

about:
  home: https://github.com/siboles/lsmgridtrack
  summary: 'A Python module providing a framework for deformable image registration of 3D images from multiphoton laser scanning microscopy. It is aimed at a technique involving the photobleaching of a 3D grid onto the image and then observing this grid region in unloaded and loaded states.
'
  license: BSD Clause-3
