{% set version = "0.4" %}
package:
  name: lsmgridtrack
  version: {{ version }}

source:
  git_url: https://github.com/siboles/lsmgridtrack.git
  git_rev: v{{ version }}

build:
  script: {{ PYTHON}} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - pytest
    - hypothesis
  run:
    - python 
    - simpleitk
    - vtk 
    - numpy
    - pydantic
    - pandas
    - openpyxl

test:
  imports:
    - lsmgridtrack

about:
  home: https://github.com/siboles/lsmgridtrack
  summary: 'A Python module providing a framework for deformable image registration of 3D images from multiphoton laser scanning microscopy. It is aimed at a technique involving the photobleaching of a 3D grid onto the image and then observing this grid region in unloaded and loaded states.
'
  license: BSD Clause-3
