name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up conda environment with Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          python-version: '3.10'
          activate-environment: lsm-dev
          environment-file: environment-dev.yml
          miniforge-variant: Mambaforge
      - shell: bash -el {0}
        run: |
          cd lsmgridtrack/test
          coverage run -m pytest test_image.py test_kinematics.py test_kinematics2d.py test_postprocessing.py test_registration.py
          coverage xml -i
          coverage report -m

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
